### ISSUE TITLE
Issues compiling main.c

### ISSUE THREAD

**Issue by alpetric** [schoppmp/linreg-mpc#8]
I'm trying to compile but I get an error while compiling "main"

```
mkdir -p obj && cc -O3 -g -Werror -I src -I /home/alex/Obliv-C/obliv-c/src/ext/oblivc -std=c11 -D_POSIX_C_SOURCE=201605L -DBIT_WIDTH_32=0 -c src/main.c -o obj/main.o
In file included from src/main.c:15:0:
src/input.h:17:31: error: unknown type name ‘obliv’
 dcrRecvIntArray(DualconR* con,obliv ufixed_t* input,size_t n,int party)
                               ^
Makefile:60: recipe for target 'obj/main.o' failed
make: *** [obj/main.o] Error 1
```

Installed Obliv-C and ran their samples (and set the OBLIVC_PATH variable as you can see that the compiler flags above seem correct, though its failing while using cc and not bin/oblivcc...)

Also Installed the two protobuf and openssl dependencies...

```
$ protoc-c --version
protobuf-c 1.2.1
libprotoc 2.6.1
```

Any ideas / hints / pointers? I must be doing something wrong here....

**Comment by schoppmp** [comment]
It seems like this is due to a recent change in obliv-c which causes `__oblivious_c` to always be defined:
https://github.com/samee/obliv-c/commit/c95d0eb612fba0d9cb50d7ae05bb8cde57605f56
Slitting up `input.h` into two headers `.h` and `.oh`, the second only used by obliv-c code, should mitigate this.
